# exceptions.py

class LPFValidationError(Exception):
    pass
